const BELT = [0, 100000, 250000, 500000, 1000000, 10000000];
const TOTAL_GANHOS = 0;
const VALOR_PRODUTO = 0;
const COMISSAO_AFILIADO = 0/100;
const COMISSAO_PARCEIROS = 0/100;
const TAXA_VENDA_AFILIADO = VALOR_PRODUTO * 0.089;
const TAXA_VENDA_PRODUTOR = VALOR_PRODUTO * 0.049;

function funcaoGanhosPorFatura() {

    let GANHOS_POR_FATURA;

if(COMISSAO_AFILIADO > 0 && COMISSAO_PARCEIROS === 0) {

    const VALOR_PRODUTO_TAXA_DESCONTADA = (VALOR_PRODUTO - TAXA_VENDA_AFILIADO - 1);

    GANHOS_POR_FATURA = VALOR_PRODUTO_TAXA_DESCONTADA - (COMISSAO_AFILIADO * VALOR_PRODUTO_TAXA_DESCONTADA);

    return GANHOS_POR_FATURA;

}
    if(COMISSAO_AFILIADO > 0 && COMISSAO_PARCEIROS > 0) {

        const VALOR_PRODUTO_TAXA_DESCONTADA = (VALOR_PRODUTO - TAXA_VENDA_AFILIADO - 1);

        const VALOR_PRODUTO_COMISSAO_AFILIADO_DESCONTADA = VALOR_PRODUTO_TAXA_DESCONTADA - (COMISSAO_AFILIADO * VALOR_PRODUTO_TAXA_DESCONTADA);

        GANHOS_POR_FATURA = VALOR_PRODUTO_COMISSAO_AFILIADO_DESCONTADA - (COMISSAO_PARCEIROS * VALOR_PRODUTO_COMISSAO_AFILIADO_DESCONTADA)
    
        return GANHOS_POR_FATURA;
    
    }
        if(COMISSAO_AFILIADO === 0 && COMISSAO_PARCEIROS === 0){
            
            GANHOS_POR_FATURA = (VALOR_PRODUTO - TAXA_VENDA_PRODUTOR - 1);

            return GANHOS_POR_FATURA;

        }
            if(COMISSAO_AFILIADO === 0 && COMISSAO_PARCEIROS > 0){

                const VALOR_PRODUTO_TAXA_DESCONTADA = (VALOR_PRODUTO - TAXA_VENDA_PRODUTOR - 1);

                GANHOS_POR_FATURA = VALOR_PRODUTO_TAXA_DESCONTADA - (COMISSAO_PARCEIROS * VALOR_PRODUTO_TAXA_DESCONTADA );

                return GANHOS_POR_FATURA;

            }

}

console.log(funcaoGanhosPorFatura());

